export const dummyEvents = [
    {
        id: 1,
        slug: "tech-conference-2024",
        title: "Tech Conference 2024",
        description:
            "Annual technology conference featuring industry leaders and innovative showcases.",
        thumbnail: "/images/events/tech-conf.jpg",
        start_date: new Date("2025-04-03"),
        end_date: new Date("2025-04-11"),
        organization: "PUFA Computing",
        organization_id: 1,
        location: "Main Auditorium",
        max_registration: 200,
        status: "upcoming",
        user_id: "1",
        created_at: new Date("2024-01-01"),
        updated_at: new Date("2024-01-01"),
        registered_count: 0,
        is_registered: false,
        author: "John Doe",
        total_registered: 0,
    },
    {
        id: 2,
        slug: "design-expo-2024",
        title: "Design Expo 2024",
        description:
            "Showcasing the latest trends in graphic design, UX/UI, and creative technologies.",
        thumbnail: "/images/events/design-expo.jpg",
        start_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        end_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        organization: "PUMA IT",
        organization_id: 2,
        location: "Exhibition Hall B",
        max_registration: 150,
        status: "upcoming",
        user_id: "2",
        created_at: new Date("2024-01-10"),
        updated_at: new Date("2024-01-15"),
        registered_count: 42,
        is_registered: true,
        author: "Jane Smith",
        total_registered: 42,
    },
    {
        id: 3,
        slug: "startup-pitch-competition",
        title: "Startup Pitch Competition",
        description:
            "Early-stage startups compete for funding and mentorship opportunities.",
        thumbnail: "/images/events/startup-pitch.jpg",
        start_date: new Date("2024-04-05"),
        end_date: new Date("2024-04-05"),
        organization: "PUMA IT",
        organization_id: 3,
        location: "Innovation Center",
        max_registration: 100,
        status: "upcoming",
        user_id: "3",
        created_at: new Date("2024-01-20"),
        updated_at: new Date("2024-01-25"),
        registered_count: 78,
        is_registered: false,
        author: "Michael Johnson",
        total_registered: 78,
    },
];
